# Site settings
title: Pipoca Cafeinada
email: jonathan.santosaugusto@gmail.com
description: >-
  Olá, bem vindo ao Pipoca Cafeinada, este é um blog sobre Programação, Jogos, Arte, Música, Modelagem e Animação 3D, Filmes, Séries, Ensino e várias outras coisas. Espero que se divirta com o conteúdo daqui tanto quanto eu.
baseurl: ""
url: "http://pipocacafeinada.com.br"
twitter_username: AqueleDevLa
github_username:  jonathan-santos

# Build settings
port: 4000
markdown: kramdown